{{- if .Values.kafka.secretConfig -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kafka-mirrormaker.fullname" . }}-secret-config
  labels:
    {{- include "kafka-mirrormaker.labels" . | nindent 4 }}
data:
    mm-secrets.properties: |+
      {{- $properties := "" }}
      {{- range $key, $value := .Values.kafka.secretConfig }}
      {{- $properties = printf "%s%s = %s\n" $properties $key $value }}
      {{- end }}
      {{ $properties | b64enc }}
{{- end }}